version: '3.4'

services:
  cargos-mongodb:
    image: mongo:4.2.3-bionic
    container_name: cargos-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=cargos
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
  service-b:
    build: .
    container_name: service-b
    network_mode: host
    ports:
      - "8081:8081"

volumes:
  mongodb:
  mongoconfig:

