openapi: "3.0.0"
info:
  version: 1.0.0
  title: Service B
  description: API for Retrieving Daily Manifest File

  contact:
    name: Ibrahim Khidr
    email: akhidrb@gmail.com

servers:
  - url: http://localhost:8081/

components:
  schemas:
    Error:
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            type: string

    GetCargosResult:
      type: object
      properties:
        cargos:
          type: array
          items:
            type: object
      required:
        - cargos

paths:
  '/cargos':
    get:
      summary: Get Daily Manifest File of Cargos
      operationId: GetDailyManifest
      responses:
        '200':
          description: Daily Manifest
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GetCargosResult'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        'default':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

